---
abstract: 'Human readable date periods'
author:
  - 'Peter Stuifzand <peter@stuifzand.eu>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Date-Period-Human
provides:
  Date::Period::Human:
    file: lib/Date/Period/Human.pm
    version: v0.4.0
requires:
  Date::Calc: 0
  DateTime: 0
resources:
  license: http://dev.perl.org/licenses/
version: v0.4.0
